### ISSUE TITLE
Does video record exist?

### ISSUE THREAD

**Issue by arrilot** [azPHP/async-guzzle-demos-2020#1]
@jeremeamia sorry to bother you, but the record of your talk does not seem to be uploaded to [azPHP YouTube channel](https://www.youtube.com/channel/UCwb1SwZ4XvBQHTk9eAPYrOQ)

Does it exist? Could you please share it somehow?

**Comment by jeremeamia** [comment]
@arrilot It looks like that presentation did not get record or had an error in the recording. Sorry. There is a link to the slides on the README. If you have any other questions, let me know.

**Comment by arrilot** [comment]
Loved it a lot, thanks!
